### ISSUE TITLE
Trouble executing ceph-dash.py on CentOS 6.5

### ISSUE THREAD

**Issue by richarson** [Crapworks/ceph-dash#1]
Hi, I'm getting an error running ./ceph-dash.py on CentOS 6.5, python is 2.6 but I'm not sure if that's supported.

The error I'm getting is:

[root@mon01 ~/ceph-dash] # ./ceph-dash.py
Traceback (most recent call last):
  File "./ceph-dash.py", line 129, in <module>
    main()
  File "./ceph-dash.py", line 124, in main
    app = CephAPI(**name**)
  File "./ceph-dash.py", line 94, in **init**
    self.jinja_env.filters['fmtbytes'] = fmtbytes
  File "/usr/lib/python2.6/site-packages/flask/helpers.py", line 769, in **get**
    value = self.func(obj)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 561, in jinja_env
    rv = self.create_jinja_environment()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 635, in create_jinja_environment
    rv = Environment(self, *_options)
  File "/usr/lib/python2.6/site-packages/flask/templating.py", line 42, in **init**
    BaseEnvironment.**init**(self, *_options)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 269, in **init**
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 73, in load_extensions
    extension = import_string(extension)
  File "/usr/lib64/python2.6/site-packages/jinja2/utils.py", line 195, in import_string
    return getattr(**import**(module, None, None, [obj]), obj)
AttributeError: 'module' object has no attribute 'autoescape

Thanks in advance for any help!

**Comment by ksingh7** [comment]
My Vote to the answer , yes this problem solves after upgrading jinja2 on CentOS based machines
