### ISSUE TITLE
socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mileskuo** [Crapworks/ceph-dash#13]
I just wanted to try the ceph-dash in my openstack env. But seemed the port 5000 has been used for other app. How to change the port for ceph-dash?

root@node-3:~/ceph-dash# ./ceph-dash.py

 * Running on http://0.0.0.0:5000/

Traceback (most recent call last):
  File "./ceph-dash.py", line 203, in <module>
    main()
  File "./ceph-dash.py", line 199, in main
    app.run(debug=False, host='0.0.0.0')
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 614, in run_simple
    inner()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 596, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 405, in make_server
    passthrough_errors, ssl_context)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 331, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by Crapworks** [comment]
Hi milesuko,

this question has been already asked here:
https://github.com/Crapworks/ceph-dash/issues/10

Does that solve your problem?
