### ISSUE TITLE
error: [Errno 98] Adresse déjà utilisée

### ISSUE THREAD

**Issue by iness25** [Crapworks/ceph-dash#49]
ça fait une semaine que cet erreur me parait dans le console de l'eclipse et j'arrive pas à la résoudre, veuillez m'aider SVP!

2017-02-09 20:42:27,430 4361 INFO ? openerp: OpenERP version 9.0c
2017-02-09 20:42:27,430 4361 INFO ? openerp: addons paths: ['/home/lenovo/.local/share/Odoo/addons/9.0', u'/home/lenovo/git/odoo/openerp/addons', u'/home/lenovo/git/odoo/addons']
2017-02-09 20:42:27,430 4361 INFO ? openerp: database: default@default:default
2017-02-09 20:42:27,507 4361 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread openerp.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lenovo/git/odoo/openerp/service/server.py", line 247, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/home/lenovo/git/odoo/openerp/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/home/lenovo/git/odoo/openerp/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Adresse déjà utilisée

**Comment by Crapworks** [comment]
I am sorry, but I don't speak french. But from what I can see, it seems like port 5000 is already in use on the system you want to start ceph-dash. Please check the FAQ to see how you can change the port number:

https://github.com/Crapworks/ceph-dash#user-content-faq

**Comment by Crapworks** [comment]
I think it is safe to close this...
