### ISSUE TITLE
Apache wsgi connect problem 

### ISSUE THREAD

**Issue by cephbrasil** [Crapworks/ceph-dash#62]
Hello! 

I try to configure my Apache to configure WSGI with Ceph Dash and I just receive this error bellow: 

```bash
[Thu Apr 04 15:01:06.595353 2019] [wsgi:error] [pid 446881:tid 140022386288384] Traceback (most recent call last):
[Thu Apr 04 15:01:06.595358 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Thu Apr 04 15:01:06.595362 2019] [wsgi:error] [pid 446881:tid 140022386288384]     response = self.full_dispatch_request()
[Thu Apr 04 15:01:06.595365 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Apr 04 15:01:06.595368 2019] [wsgi:error] [pid 446881:tid 140022386288384]     rv = self.handle_user_exception(e)
[Thu Apr 04 15:01:06.595371 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Apr 04 15:01:06.595375 2019] [wsgi:error] [pid 446881:tid 140022386288384]     reraise(exc_type, exc_value, tb)
[Thu Apr 04 15:01:06.595377 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Apr 04 15:01:06.595380 2019] [wsgi:error] [pid 446881:tid 140022386288384]     rv = self.dispatch_request()
[Thu Apr 04 15:01:06.595383 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Thu Apr 04 15:01:06.595386 2019] [wsgi:error] [pid 446881:tid 140022386288384]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 04 15:01:06.595389 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/views.py", line 84, in view
[Thu Apr 04 15:01:06.595406 2019] [wsgi:error] [pid 446881:tid 140022386288384]     return self.dispatch_request(*args, **kwargs)
[Thu Apr 04 15:01:06.595411 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/usr/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
[Thu Apr 04 15:01:06.595417 2019] [wsgi:error] [pid 446881:tid 140022386288384]     return meth(*args, **kwargs)
[Thu Apr 04 15:01:06.595420 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "/var/www/html/ceph-dash/contrib/wsgi/../../app/dashboard/views.py", line 112, in get
[Thu Apr 04 15:01:06.595423 2019] [wsgi:error] [pid 446881:tid 140022386288384]     with Rados(**self.clusterprop) as cluster:
[Thu Apr 04 15:01:06.595426 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "rados.pyx", line 595, in rados.Rados.__enter__ (/build/ceph-10.2.9/src/build/rados.c:7527)
[Thu Apr 04 15:01:06.595429 2019] [wsgi:error] [pid 446881:tid 140022386288384]   File "rados.pyx", line 785, in rados.Rados.connect (/build/ceph-10.2.9/src/build/rados.c:10073)
[Thu Apr 04 15:01:06.595432 2019] [wsgi:error] [pid 446881:tid 140022386288384] ObjectNotFound: error connecting to the cluster
```

When I try to access http://cephdash:5000 in my environment that's work without problem. 

Ubuntu 16.04.2 LTS
Apache/2.4.18 (Ubuntu)

**Comment by cephbrasil** [comment]
Hi I look here and it's just my wrong configuration. 

I closing this issue.
